(async()=>{const p=await GDFC.approved();if(!p||!['owner','admin','moderator'].includes(p.role)){content.innerHTML='<div class="panel"><p>Staff access required.</p></div>';return}
async function load(){const [members,tournaments,matches]=await Promise.all([sb.from('profiles').select('id,name,username,email,phone,efootball_id,status,role,created_at').order('created_at',{ascending:false}),sb.from('tournaments').select('*').order('created_at',{ascending:false}),sb.from('tournament_matches').select('*').eq('status','pending_admin').order('created_at',{ascending:false})]);
content.innerHTML=`<div class="panel"><h2>Member approvals</h2>${(members.data||[]).map(x=>`<div class="item"><div><b>${GDFC.esc(x.name||x.username)}</b><small>${GDFC.esc(x.email)} • ${GDFC.esc(x.efootball_id)} • ${GDFC.esc(x.role)}</small></div><span>${GDFC.esc(x.status)}</span>${x.status==='pending'?`<button class="btn gold" data-status="approved" data-id="${x.id}">Approve</button><button class="btn" data-status="rejected" data-id="${x.id}">Reject</button>`:''}</div>`).join('')||'<p>No members.</p>'}</div>
<div class="panel"><h2>Create tournament</h2><form id="create-tournament"><label>Title<input id="t-title" required></label><label>Description<textarea id="t-desc"></textarea></label><label>Start time<input id="t-start" type="datetime-local" required></label><label>Mode<select id="t-mode"><option value="tree">World Cup bracket</option><option value="league">League</option></select></label><label>Max players<input id="t-cap" type="number" min="2" max="32" value="16" required></label><button class="btn gold">Create & open registration</button></form></div>
<div class="panel"><h2>Tournaments</h2>${(tournaments.data||[]).map(t=>`<div class="item"><div><b>${GDFC.esc(t.title)}</b><small>${GDFC.esc(t.mode)} • ${t.max_players} players • ${GDFC.esc(t.status)}</small></div><a class="btn" href="tournament.html?id=${t.id}">View</a>${t.mode==='tree'&&t.status==='open'?`<button class="btn gold" data-bracket="${t.id}">Generate bracket</button>`:''}</div>`).join('')||'<p>No tournaments.</p>'}</div>
<div class="panel"><h2>Pending match results</h2>${(matches.data||[]).map(m=>`<div class="item"><div><b>${GDFC.esc(m.player1_id||'TBD')} vs ${GDFC.esc(m.player2_id||'TBD')}</b><small>Submitted: ${GDFC.time(m.submitted_at)}</small></div><button class="btn gold" data-match="${m.id}" data-p1="${m.player1_id||''}" data-p2="${m.player2_id||''}">Approve result</button></div>`).join('')||'<p>No pending results.</p>'}</div>`;
document.querySelectorAll('[data-status]').forEach(b=>b.onclick=async()=>{b.disabled=true;const r=await sb.rpc('admin_set_member_status',{p_user_id:b.dataset.id,p_status:b.dataset.status});if(r.error)alert(r.error.message);else await load()});
document.querySelector('#create-tournament').onsubmit=async e=>{e.preventDefault();const r=await sb.rpc('admin_create_tournament',{p_title:document.querySelector('#t-title').value.trim(),p_description:document.querySelector('#t-desc').value.trim(),p_start_at:new Date(document.querySelector('#t-start').value).toISOString(),p_max_players:Number(document.querySelector('#t-cap').value),p_mode:document.querySelector('#t-mode').value});if(r.error)alert(r.error.message);else{alert('Tournament created and opened for registration.');await load()}};
document.querySelectorAll('[data-bracket]').forEach(b=>b.onclick=async()=>{b.disabled=true;const r=await sb.rpc('generate_bracket',{p_tournament_id:b.dataset.bracket});if(r.error)alert(r.error.message);else{alert(`Bracket generated (${r.data?.bracket_size||''} slots).`);await load()}});
document.querySelectorAll('[data-match]').forEach(b=>b.onclick=async()=>{const s1=prompt('Player 1 score','0'),s2=prompt('Player 2 score','0');if(s1===null||s2===null)return;const p1=b.dataset.p1,p2=b.dataset.p2;let winner=null;if(Number(s1)>Number(s2))winner=p1;else if(Number(s2)>Number(s1))winner=p2;else winner=prompt('Draw: enter winner player UUID, or leave blank for no winner','');const r=await sb.rpc('approve_match_result',{p_match_id:b.dataset.match,p_winner:winner||null,p_score1:Number(s1),p_score2:Number(s2)});if(r.error)alert(r.error.message);else await load()});
}
load();
sb.channel('gdfc-admin-live').on('postgres_changes',{event:'*',schema:'public',table:'profiles'},load).on('postgres_changes',{event:'*',schema:'public',table:'tournament_matches'},load).subscribe();
})()